--Friendlist for Azzy AI
--Automatically generated by Azzy AI.
--To add friends, put mercenary or homun into standby mode (ctl+T or alt+T as appropriate), and sit 1 cell to the west (to left in default view) of the person who you wish to friend
--To remove friends, put merc/homun into standby mode, and sit 1 cell to the east (to right in default view) of the person you want to remove.
--
--To add KOS/Enemy/Etc lists, get the ID number from ROPD or by friending them, and make a line like
--MyFriends{2322797}=KOS
--Possible values are NEUTRAL, KOS (kill on sight), ENEMY (assume hostile, but don't attack), and ALLY (assume friendly).
MyFriends={}
MyFriends[2003516]=1 -- 
MyFriends[110371312]=1 -- 
MyFriends[1529417]=1 -- 
MyFriends[2000028]=1 -- 
MyFriends[111873449]=1 -- 
MyFriends[110005661]=1 -- 
