MyTact={}
MyTact[0]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_REACT,CAST_REACT,PUSH_NEVER,DEBUFF_ANY_A,CLASS_BOTH,RESCUE_RETAINER,-1,SNIPE_OK,KS_NEVER,1,CHASE_ALWAYS} --Default
MyTact[10]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_REACT,CAST_REACT,PUSH_NEVER,DEBUFF_NEVER,CLASS_BOTH,RESCUE_RETAINER,-1,SNIPE_OK,KS_NEVER,1,CHASE_NORMAL} --Default Summon
MyTact[11]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_NEVER,CAST_PASSIVE,PUSH_NEVER,DEBUFF_NEVER,CLASS_BOTH,RESCUE_NEVER,-1,SNIPE_OK,KS_NEVER,1,CHASE_ALWAYS} --Autodetect Plant 
MyTact[3010]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_REACT,CAST_REACT,PUSH_NEVER,DEBUFF_NEVER,CLASS_BOTH,RESCUE_SELF,-1,SNIPE_OK,KS_NEVER,1,CHASE_ALWAYS} --Goldring
TactLastSavedDate        = "06/01/2024 15:26:51"